name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - '8.0'
        laravel:
          - 8.*
        prefer:
          - 'prefer-lowest'
          - 'prefer-stable'
        include:
          - laravel: '8.*'
            testbench: '6.*'

    name: PHP ${{ matrix.php }} and ${{ matrix.stack }} - Laravel ${{ matrix.laravel }} --${{ matrix.prefer }}

    steps:
    - uses: actions/checkout@v2.4.0

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
        coverage: pcov

    - uses: actions/cache@v2.1.6
      name: Cache dependencies
      with:
        path: ~/.composer/cache/files
        key: composer-php-${{ matrix.php }}-${{ matrix.laravel }}-${{ matrix.prefer }}-${{ hashFiles('composer.json') }}

    - name: Install dependencies
      run: |
        composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" "orchestra/database:${{ matrix.testbench }}" "doctrine/dbal:^2.9" --no-interaction --no-update
        composer update --${{ matrix.prefer }} --prefer-dist --no-interaction --no-suggest

    # - name: Run static analysis
    #   run: |
    #     vendor/bin/psalm

    - name: Run tests
      run: |
        vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml
      env:
        STRIPE_SECRET: ${{ secrets.STRIPE_SECRET }}

    - uses: codecov/codecov-action@v2.1.0
      with:
        fail_ci_if_error: false
